services:
  pos-front:
    image: fahdbouaicha/pos_front:v0.0.1
    container_name: pos-front-test
    ports:
      - "3001:3001"
    environment:
      - VITE_API_KEY=c7a2a4fbb145def05dfa52374c932ce9c66ed6ee095295efe36eee4d4562de81
      - VITE_BASE_URL=http://localhost:8000/api
    restart: always  # Ensure container restarts on crashes
